name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Test
      run: make test
    #- name: Lint
    #  run: make lint

